/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mitre.opensextant.desktop.ui.forms.panels;


/**
 *
 * @author aquina
 */
@SuppressWarnings("serial")
public class RowButtons extends javax.swing.JPanel {

    /**
     * Creates new form RowButtons
     */
    public RowButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelDeleteButton = new javax.swing.JButton();
        reRunButton = new javax.swing.JButton();
        viewResultsButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setLayout(new java.awt.GridLayout(1, 0));

        cancelDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mitre/opensextant/desktop/icons/cancelCircle.png"))); // NOI18N
        add(cancelDeleteButton);

        reRunButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mitre/opensextant/desktop/icons/rerun.png"))); // NOI18N
        reRunButton.setEnabled(false);
        add(reRunButton);

        viewResultsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mitre/opensextant/desktop/icons/eye.png"))); // NOI18N
        viewResultsButton.setEnabled(false);
        add(viewResultsButton);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton cancelDeleteButton;
    protected javax.swing.JButton reRunButton;
    protected javax.swing.JButton viewResultsButton;
    // End of variables declaration//GEN-END:variables
    
    
}
