/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mitre.opensextant.desktop.ui.forms.panels;

/**
 *
 * @author aquina
 */
public class RowDuration extends javax.swing.JPanel {

    /**
     * Creates new form RowDuration
     */
    public RowDuration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        durationLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        durationLabel.setText(" ");
        durationLabel.setMaximumSize(new java.awt.Dimension(120, 20));
        durationLabel.setMinimumSize(new java.awt.Dimension(120, 20));
        durationLabel.setPreferredSize(new java.awt.Dimension(120, 20));
        durationLabel.setSize(new java.awt.Dimension(120, 20));
        add(durationLabel, "card2");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel durationLabel;
    // End of variables declaration//GEN-END:variables
}
