/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mitre.opensextant.desktop.ui.forms.panels;

/**
 *
 * @author aquina
 */
@SuppressWarnings("serial")
public class RowProgressBar extends javax.swing.JPanel {

    /**
     * Creates new form RowProgressBar
     */
    public RowProgressBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(60, 30));
        setLayout(new java.awt.CardLayout());

        progressBar.setMinimumSize(new java.awt.Dimension(50, 20));
        progressBar.setString("Queued: 0%");
        progressBar.setStringPainted(true);
        add(progressBar, "card2");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
